artifact_uri: /workspaces/codespaces-blank/MLFLOW_TRACKING_URI=https:/dagshub.com/VedantMandre/Chest-Disease-Prediction-Project.mlflow/0/7f7bfb9e256048c48d8ef077d6c064d9/artifacts
end_time: 1715732808344
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 7f7bfb9e256048c48d8ef077d6c064d9
run_name: agreeable-worm-7
run_uuid: 7f7bfb9e256048c48d8ef077d6c064d9
source_name: ''
source_type: 4
source_version: ''
start_time: 1715732803058
status: 4
tags: []
user_id: codespace
