artifact_uri: /workspaces/codespaces-blank/MLFLOW_TRACKING_URI=https:/dagshub.com/VedantMandre/Chest-Disease-Prediction-Project.mlflow/0/9c330a449957488a97e6e8dceee6f38d/artifacts
end_time: 1715732408972
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 9c330a449957488a97e6e8dceee6f38d
run_name: honorable-hare-450
run_uuid: 9c330a449957488a97e6e8dceee6f38d
source_name: ''
source_type: 4
source_version: ''
start_time: 1715732401678
status: 4
tags: []
user_id: codespace
