artifact_location: /workspaces/codespaces-blank/MLFLOW_TRACKING_URI=https:/dagshub.com/VedantMandre/Chest-Disease-Prediction-Project.mlflow/0
creation_time: 1715732401481
experiment_id: '0'
last_update_time: 1715732401481
lifecycle_stage: active
name: Default
